# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-04-07 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='img',
            field=models.CharField(max_length=200),
        ),
    ]
