# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-04-07 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascraper', '0003_auto_20210407_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='img',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
